  
name: "Terraform Module CI"

on: workflow_dispatch

defaults:
  run:
    working-directory: ./tests

jobs:
  terraform:
    name: Terraform Run
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Terraform Setup
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.3
          cli_config_credentials_hostname: 'app.terraform.io'
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
          terraform_wrapper: true
       
      - name: Terraform Format
        id: fmt
        run: terraform fmt -check

      - name: Terraform Init
        id: init
        run: terraform init

      - name: Terraform Speculative Plan
        id: plan
        run: terraform plan -no-color
        continue-on-error: false

      - name: Terraform Plan and Apply
        id: apply
        run: terraform apply -auto-approve
        continue-on-error: true

      - name: Terraform Destroy
        id: destroy
        run: terraform destroy -force